src/BibliotecaMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Haila Michaele Pelloso";

            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/BibliotecaMVC/ViewComponents/ListagemLivrosViewComponent.cs
using BibliotecaMVC.Data;
using BibliotecaMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaMVC.ViewComponents
{
    public class ListagemLivrosViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public ListagemLivrosViewComponent(ApplicationDbContext c)
        {
            _context = c;
        }

        public async Task<IViewComponentResult> InvokeAsync(int autorID)
        {
            var produtos = await GetListagemLivrosAsync(autorID);
            return View(produtos);
        }

        private Task<IEnumerable<Livro>> GetListagemLivrosAsync(int autorID)
        {
            var livros = _context.Livro.AsNoTracking()
                        .Include(l => l.LivroAutor)
                        .ThenInclude(li => li.Autor)
                        .OrderBy(l => l.Titulo);

            if (autorID != 0)
                livros.Where(x => x.LivroAutor.Any(y => y.AutorID == autorID));

            return Task.FromResult(livros.AsEnumerable());
        }
    }
}

src/BibliotecaMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<br />
<h3>FIB - Faculdades Integradas de Bauru</h3>
<h4>MBA em Engenharia de Software</h4>
<p><b>Disciplina: </b>.NET Avançado</p>
<p><b>Professor: </b>Victor de Assis Rodrigues</p>
<p><b>Projeto: </b>Biblioteca Virtual</p>

src/BibliotecaMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contato";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<h4>Haila Michaele Pelloso</h4>

<address>
    <strong>Telefone:</strong> (14) 98133-0081<br />
    <strong>E-mail:</strong> <a href="mailto:hailapelloso@yahoo.com.br">hailapelloso@yahoo.com.br</a><br />
</address>

src/BibliotecaMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<br />
<p class="lead">Verifique os livros da nossa Biblioteca abaixo.</p>

<div>
    @await Component.InvokeAsync("ListagemLivros", "")
</div>